---
- name: install firefox-esr
  apt:
    state: latest
    name: "{{ item }}" 
  loop:
    - firefox-esr
    - wget
    - jq

- name: Download firefox-extension-manager
  # get_url: url="https://raw.githubusercontent.com/Apfelwurm/ubuntu-scripts/master/mozilla/firefox-extension-manager" dest=/usr/local/bin/firefox-extension-manager validate_certs=no mode=0755 force=yes
  get_url: url="https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/mozilla/firefox-extension-manager" dest=/usr/local/bin/firefox-extension-manager validate_certs=no mode=0755 force=yes
    
- name: get firefox profile folder
  shell: echo $(find /home/{{ firefox_username }}/.mozilla -name "*default-esr")
  register: firefoxdefaultprofile

# - name: install firefox store xpis
#   debug: 
#     msg: "{{ item }}"
#   loop: "{{ extensions_urlbuilder }}"

- name: install firefox store xpis
  shell: /usr/local/bin/firefox-extension-manager --install --url $({{ item.value.urlbuilder }}) --path {{ firefoxdefaultprofile.stdout }}$(echo "/extensions")
  become: true
  become_method: su
  become_user: "{{ firefox_username }}"
  with_dict: "{{ extensions }}"

- name: enable firefox xpis
  shell: jq '.addons[] |= ((select(.id=="{{ item.value.id }}") | .active=true | .userDisabled=false))' {{ firefoxdefaultprofile.stdout }}$(echo "/extensions.json") > /tmp/hallo
  become: true
  become_method: su
  become_user: "{{ firefox_username }}"
  with_dict: "{{ extensions }}"


# > {{ firefoxdefaultprofile.stdout }}$(echo "/extensions.json")
