---
- name: install firefox-esr
  apt:
    state: latest
    name: "{{ item }}" 
  loop:
    - firefox-esr

- name: Download firefox-extension-manager
  get_url: url="https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/mozilla/firefox-extension-manager" dest=/usr/local/bin/firefox-extension-manager validate_certs=no mode=0755 force=yes
    
- name: get firefox profile folder
  shell: echo $(find /home/{{ firefox_username }}/.mozilla -name "*default-esr")
  register: firefoxdefaultprofile

- name: install firefox store xpis
  shell: /usr/local/bin/firefox-extension-manager --install --url $({{ item }}) --path {{ firefoxdefaultprofile.stdout }}$(echo "/extensions")
  loop: extensions_urlbuilder