---
- name: determinate deb-multimedia keyring link
  shell: echo "https://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/$(curl -s https://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/ | grep -o 'deb-multimedia-keyring_[0-9]*\.[0-9]*\.[0-9]*\_all.deb' | head -1)"
  register: tempurl

- name: Install deb-multimedia keyring
  apt: deb={{ tempurl.stdout }}

- name: Add deb-multimedia repository
  ansible.builtin.apt_repository:
    repo: deb https://www.deb-multimedia.org bullseye main non-free
    state: present
    filename: deb-multimedia
  register: deb_multimedia

- name: Upgrade the OS (apt-get dist-upgrade)
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes
  when: deb_multimedia.changed

- name: install deb-multimedia packages
  apt:
    state: latest
    name: "{{ item }}" 
  loop:
    - avidemux
    - ffmpeg
    - audacity