---
- hosts: all
  vars_files:
    - vars.yml

  pre_tasks:
  - name: Check if this is the first run
    stat:
      path: /etc/ansible_was_already_executed
    register: ansible_was_already_executed_check
  - name: Set hostname of command server as fact
    set_fact: ansible_was_already_executed="{{ ansible_was_already_executed_check.stat.exists }}"
  - name: Creating a file with content
    copy:
      dest: "/home/ams/runansible.sh"
      content: |
        /usr/bin/ansible-pull -d /ansibleconfig -vvv -i /ansibleconfig/inventory -U https://github.com/amscamp/AMS_Debian_Ansible
  - name: Install packages
    apt:
      state: latest
      name: "{{ packages }}" 
  - name: crearte first run file
    file:
      path: /etc/ansible_was_already_executed
      state: touch
      mode: 0644
      owner: root
      group: root
    when: not ansible_was_already_executed


  roles:
  - role: kde-desktop
    desktop_username: "{{ username }}"
  - role: basic-applications
  - role: plymouth
  - role: terminal
    terminal_username: "{{ username }}"
    # when: ansible_was_already_executed
  - role: ansible-pull
    ansible_pull_url: https://github.com/amscamp/AMS_Debian_Ansible
