---
- hosts: all
- include_vars: vars.yml

  tasks:
  - name: Creating a file with content
    copy:
      dest: "/home/ams/knaddle"
      content: |
        line 01
        line 02
  - name: Install packages
    apt:
      state: latest
      update_cache: true
      name: "{{ packages }}" 