---
- hosts: all
  vars_files:
    - vars.yml

  pre_tasks:
  - name: Check if this is the first run
    stat:
      path: /etc/ansible_was_already_executed
    register: ansible_was_already_executed_check
  - name: Set already executed fact
    set_fact: ansible_was_already_executed="{{ ansible_was_already_executed_check.stat.exists }}"
  
  - name: Print mac
    ansible.builtin.debug:
      msg: System {{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress }}  
      
  - name: not in list
    ansible.builtin.debug:
      msg: not in list
    when: hostvars[inventory_hostname].ansible_default_ipv4.macaddress not in macs  
  
  - name: in list
    ansible.builtin.debug:
      msg: in list
    when: hostvars[inventory_hostname].ansible_default_ipv4.macaddress in macs

  - name: fail if not in list
    ansible.builtin.fail:
      msg: The system is not allowed to run this
    when: ansible_was_already_executed and hostvars[inventory_hostname].ansible_default_ipv4.macaddress not in macs

  - name: crearte first run file
    file:
      path: /etc/ansible_was_already_executed
      state: touch
      mode: 0644
      owner: root
      group: root
    when: not ansible_was_already_executed


  roles:
  - role: computername
  - role: ssh
    ssh_username: "{{ username }}"
  - role: kde-desktop
    desktop_username: "{{ username }}"
  - role: kde-desktop-customisation
    desktop_username: "{{ username }}"
    when: ansible_was_already_executed
  - role: basic-applications
  - role: t460s
  - role: plymouth
  - role: terminal
    terminal_username: "{{ username }}"
    when: ansible_was_already_executed
  - role: pull-journal-central-client
    pjc_base_url: "https://pjc.volzit.de"
    pjc_organisation_id: "2"
    pjc_organisation_password: "ZIy9qMyyT3AtiSML0EyXGey66oaerXehqeet24OVeZsbjuNx5IxAY1Yu7nnAM9UO"
    when: ansible_was_already_executed
  - role: ansible-pull
    ansible_pull_url: https://github.com/amscamp/AMS_Debian_Ansible
    pull_username: "{{ username }}"
  - role: media-applications
    when: ansible_was_already_executed
  - role: master-pdf-editor
  - role: zoom
  - role: chromium
    extensions:
      - "cjpalhdlnbpafiamejdnhcphjbkeiagm" #ublock  
  - role: firefox
    extensions:
      - id: "uBlock0@raymondhill.net"
        url: "https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi"
  - role: signal-desktop
  - role: printer
    print_username: "{{ username }}"
  - role: printerdetection
  - role: password-mgmt
    password_username: "{{ username }}"
    default_entries:
      - key: "Encryption"
        value: "amscampboot"  
      - key: "RootPW"
        value: "ams"
      - key: "UserPW"
        value: "ams"
    when: ansible_was_already_executed
  - role: wifi
    ssids:
      - ssid: "fest.spiel.haus"
        initialpass: "password"
        prio: 0
      - ssid: "AMS-AP01"
        initialpass: "password"
        prio: 0
    when: ansible_was_already_executed

