---
- hosts: all
  vars_files:
    - vars.yml

  tasks:
  - name: Creating a file with content
    copy:
      dest: "/home/ams/runansible.sh"
      content: |
        /usr/bin/ansible-pull -d /ansibleconfig -vvv -i /ansibleconfig/inventory -U https://github.com/amscamp/AMS_Debian_Ansible
  - name: Install packages
    apt:
      state: latest
      name: "{{ packages }}" 

  roles:
  - role: plymouth
  - role: terminal
    terminal_username: "{{ username }}"
  - role: ansible-pull
    ansible_pull_url: https://github.com/amscamp/AMS_Debian_Ansible