---
- hosts: all
  vars_files:
    - vars.yml

  pre_tasks:
  - name: Check if this is the first run
    stat:
      path: /etc/ansible_was_already_executed
    register: ansible_was_already_executed_check
  - name: Set hostname of command server as fact
    set_fact: ansible_was_already_executed="{{ ansible_was_already_executed_check.stat.exists }}"
  - name: Install packages
    apt:
      state: latest
      name: "{{ packages }}" 
  - name: crearte first run file
    file:
      path: /etc/ansible_was_already_executed
      state: touch
      mode: 0644
      owner: root
      group: root
    when: not ansible_was_already_executed


  roles:
  # - role: kde-desktop
  #   desktop_username: "{{ username }}"
  # - role: kde-desktop-customisation
  #   desktop_username: "{{ username }}"
  #   when: ansible_was_already_executed
  # - role: basic-applications
  # - role: t460s
  # - role: plymouth
  # - role: terminal
  #   terminal_username: "{{ username }}"
  #   when: ansible_was_already_executed
  # - role: ansible-pull
  #   ansible_pull_url: https://github.com/amscamp/AMS_Debian_Ansible
  #   pull_username: "{{ username }}"
  # - role: media-applications
  #   when: ansible_was_already_executed
  # - role: master-pdf-editor
  # - role: zoom
  # - role: chromium
  #   extensions:
  #     - "cjpalhdlnbpafiamejdnhcphjbkeiagm" #ublock  
  # - role: firefox
  #   extensions:
  #     - id: "uBlock0@raymondhill.net"
  #       url: "https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi"
  - role: signal
  - role: printer
    print_username: "{{ username }}"
  # - role: password-mgmt
  #   password_username: "{{ username }}"
  #   default_entries:
  #     - key: "Encryption"
  #       value: "amscampboot"  
  #     - key: "RootPW"
  #       value: "ams"
  #     - key: "UserPW"
  #       value: "ams"
  #   when: ansible_was_already_executed
  - role: wifi
    ssids:
      - key: "fest.spiel.haus"
        value: "password"
      - key: "fest.spiel.haus.gast"
        value: "password"
    when: ansible_was_already_executed

