---
- name: get password if entry exists
  shell: echo "$(pass show {{ passwd_wifi_folder }}/{{ item.key }})"  
  environment:
    HOME: "{{ wallet_userhome }}"
  when: wifi_wallet_entrys.stdout is search("{{ item.key }}")
  no_log: True
  register: "pwdtemp"
- name: create wifi {{ item.key }}
  community.general.nmcli:
    type: wifi
    conn_name: "{{ item.key }}"
    ifname: wlp4s0
    ssid: "{{ item.key }}"
    wifi_sec:
      key-mgmt: wpa-psk
      psk: "{{ pwdtemp.stdout }}"
    autoconnect: true
    state: present
  no_log: True
  when:  pwdtemp.stdout != item.value