---

- name: get wallet folder entrys
  shell: pass ls {{ passwd_wifi_folder }}
  environment:
    HOME: "{{ wallet_userhome }}"
  register: wifi_wallet_entrys
- name: create wallet entrys if they not exist
  shell: echo "{{ item.value }}" | pass insert -e {{ passwd_wifi_folder }}/{{ item.key }}
  environment:
    HOME: "{{ wallet_userhome }}"
  when: not wifi_wallet_entrys.stdout is search(item.key)
  loop: "{{ ssids }}"
- name: Create the wifi {{ item.key }}
  block:
    - name: get password if entry exists
      shell: echo "$(pass show {{ passwd_wifi_folder }}/{{ item.key }})"  
      environment:
        HOME: "{{ wallet_userhome }}"
      when: wifi_wallet_entrys.stdout is search("{{ item.key }}")
      no_log: True
      register: "pwd_{{ item.key }}"
    - name: create wifi {{ item.key }}
      community.general.nmcli:
        type: wifi
        conn_name: {{ item.key }}
        ifname: wlp4s0
        ssid: {{ item.key }}
        wifi_sec:
          key-mgmt: wpa-psk
          psk: "{{ pwd_{{ item.key }} }}"
          autoconnect: true
        state: present
      when:  "{{ pwd_{{ item.key }} }}" != item.value
   loop: {{ ssids }}