passwd_wallet: kdewallet
passwd_folder: system
wallet_username: root
password_username: user

default_entries:
  - key: "Encryption"
    value: "encryptionpw"  
  - key: "RootPW"
    value: "rootpw"
  - key: "UserPW"
    value: "userpw"