---
- name: install libreoffice packages
  apt:
    state: latest
    name: "{{ item }}" 
  loop:
    - libreoffice-help-en-us
    - libreoffice-impress
    - libreoffice-kf5
    - libreoffice-plasma
    - libreoffice-writer
    - libreoffice-calc
    - libreoffice-base
    - mythes-en-us

- name: install additional packages
  apt:
    state: latest
    name: "{{ item }}" 
  loop:
    - jq
    - gimp
    - firefox-esr
    - nextcloud-desktop
    - chromium
    - simple-scan
    - xournal
    - enigmail
    - arandr



- name: install libreoffice packages
  apt:
    state: latest
    name: "{{ item }}" 
  loop:
    - curl


- name: determinate free-pdf-editor link
  shell: echo "https://code-industry.net/public/$(curl -s https://code-industry.net/free-pdf-editor/ | grep -o 'master-pdf-editor-[0-9]*\.[0-9]*\.[0-9]*\-qt5.x86_64.deb' | head -1)"
  register: tempurl

- name: Install free-pdf-editor
  apt: deb={{ tempurl.stdout }}

- name: determinate deb-multimedia keyring link
  shell: echo "https://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/$(curl -s https://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/ | grep -o 'deb-multimedia-keyring_[0-9]*\.[0-9]*\.[0-9]*\_all.deb' | head -1)"
  register: tempurl

- name: Install deb-multimedia keyring
  apt: deb={{ tempurl.stdout }}

- name: Add deb-multimedia repository
  ansible.builtin.apt_repository:
    repo: deb https://www.deb-multimedia.org bullseye main non-free
    state: present
    filename: deb-multimedia

- name: install deb-multimedia packages
  apt:
    state: latest
    name: "{{ item }}" 
  loop:
    - avidemux
    - ffmpeg
    - audacity

- name: determinate zoom link
  shell: echo "https://zoom.us/client/$(curl -s https://zoom.us/rest/download?os=linux | jq '.result.downloadVO.zoom.version' -r)/zoom_amd64.deb"
  register: tempurl

- name: Install zoom
  apt: deb={{ tempurl.stdout }}

# - name: determinate link
#   shell: echo $({{ item.value.expr }})
#   register: tempurl
# - name: Install .deb files
#   become: yes
#   apt: deb={{ tempurl.stdout }}
