---

- name: install needed packages
  apt:
    state: latest
    name: "{{ item }}" 
  loop:
    - plasma-desktop
    - plasma-workspace
    - udisks2
    - upower
    - kwin-x11
    - sddm
    - xserver-xorg
    - ark
    - vlc
    - gwenview
    - kate
    - kcalc
    - kde-spectacle
    - khelpcenter
    - kwalletmanager
    - okular
    - plasma-dataengines-addons 
    - plasma-pa
    - plasma-runners-addons
    - plasma-wallpapers-addons
    - plasma-widgets-addons
    - polkit-kde-agent-1
    - sweeper
    - plasma-nm
    - print-manager
    - dolphin
    - kdialog
    - kfind
    - k3b
    - gdebi