---

- name: install needed packages
  apt:
    state: latest
    name: "{{ item }}" 
  loop:
    - plasma-desktop
    - plasma-workspace
    - udisks2
    - upower
    - kwin-x11
    - sddm
    - xserver-xorg
    - ark
    - dragonplayer
    - gwenview
    - juk
    - kate
    - kcalc
    - kde-spectacle
    - khelpcenter
    - kwalletmanager
    - okular
    - plasma-dataengines-addons 
    - plasma-pa
    - plasma-runners-addons
    - plasma-wallpapers-addons
    - plasma-widgets-addons
    - polkit-kde-agent-1
    - sweeper
    - plasma-nm
    - apper
    - print-manager
    - libreoffice-help-en-us
    - libreoffice-impress
    - libreoffice-kf5
    - libreoffice-plasma
    - libreoffice-writer
    - mythes-en-us