---

- name: Copy PPDs in the ppd folder
  copy:
    src: "ppd/"
    dest: "/usr/share/ppd/"
    owner: root
    group: root
    mode: 0644

# - name: Copy filter in the filter folder
#   copy:
#     src: "filter/"
#     dest: "/usr/lib/cups/filter/"
#     owner: root
#     group: root
#     mode: 0755

- name: Install .deb packages
  ansible.builtin.apt:
    deb: "{{ role_path }}/files/deb/{{ item }}"
  loop:
    - brother-udev-rule-type1-1.0.2-0.all.deb
    - brscan4-0.4.11-1.amd64.deb
    - mfcj5730dwcupswrapper-1.0.1-0.i386.deb
    - mfcj5730dwlpr-1.0.1-0.i386.deb
    - libsane-dsseries_1.0.5-1_amd64.deb

# - name: install gutenprint
#   apt:
#     state: latest
#     name: "{{ item }}" 
#   loop:
#     - printer-driver-gutenprint

- import_tasks: uld.yml
