---

- name: install apt driver
  apt:
    state: latest
    name: "{{ item }}" 
  loop:
    - hplip
  notify: 'restart cups'

- name: Adding user {{ print_username }} to lp
  user: name={{ print_username }}
        groups=lp
        append=yes

- name: Adding user {{ print_username }} to lpadmin
  user: name={{ print_username }}
        groups=lpadmin
        append=yes

- name: Copy PPDs in the ppd folder
  copy:
    src: "ppd/"
    dest: "/usr/share/ppd/"
    owner: root
    group: root
    mode: 0644
  notify: 'restart cups'

# - name: Copy filter in the filter folder
#   copy:
#     src: "filter/"
#     dest: "/usr/lib/cups/filter/"
#     owner: root
#     group: root
#     mode: 0755

- name: Check if i386 is enabled
  shell: dpkg --print-foreign-architectures | grep i386
  register: result_i386_check
  changed_when: result_i386_check.rc == 1
  failed_when: result_i386_check.rc > 1

- name: Enable i386 architecture
  command: dpkg --add-architecture i386
  when: result_i386_check.rc == 1

- name: Ensure apt cache is up to date
  apt: update_cache=yes
  when: result_i386_check.rc == 1

- name: Install .deb packages
  ansible.builtin.apt:
    deb: "{{ role_path }}/files/deb/{{ item }}"
  loop:
    - brother-udev-rule-type1-1.0.2-0.all.deb
    - brscan4-0.4.11-1.amd64.deb
    - mfcj5730dwlpr-1.0.1-0.i386.deb
    - mfcj5730dwcupswrapper-1.0.1-0.i386.deb
    - libsane-dsseries_1.0.5-1_amd64.deb
  notify: 'restart cups'

# - name: install gutenprint
#   apt:
#     state: latest
#     name: "{{ item }}" 
#   loop:
#     - printer-driver-gutenprint

- import_tasks: uld.yml

- name: Ensure CreateIPPPrinterQueues is set to All
  ansible.builtin.lineinfile:
    path: /etc/cups/cups-browsed.conf
    regexp: '^\s*#*\s*(CreateIPPPrinterQueues All.*)'
    replace: '\1'
  notify: 'restart cups-browsed'
