---
- name: get wallet folders
  shell: qdbus org.kde.kwalletd5 /modules/kwalletd5 folderList "$(qdbus org.kde.kwalletd5 /modules/kwalletd5 org.kde.KWallet.open {{ passwd_wallet }} 0 "{{ passwd_folder }}")" "{{ passwd_folder }}" 
  become: true
  become_method: su
  become_user: "{{ wallet_username }}"
  register: walletfolders

- name: create wallet folder
  shell: qdbus org.kde.kwalletd5 /modules/kwalletd5 createFolder "$(qdbus org.kde.kwalletd5 /modules/kwalletd5 org.kde.KWallet.open {{ passwd_wallet }} 0 "{{ passwd_folder }}")" "{{ passwd_folder }}" "{{ passwd_folder }}"
  become: true
  become_method: su
  become_user: "{{ wallet_username }}"
  when: not walletfolders.stdout is search(passwd_folder)



- name: get wallet folder entrys
  shell: qdbus org.kde.kwalletd5 /modules/kwalletd5 entryList "$(qdbus org.kde.kwalletd5 /modules/kwalletd5 org.kde.KWallet.open {{ passwd_wallet }} 0 "{{ passwd_folder }}")" "{{ passwd_folder }}" "{{ passwd_folder }}"
  become: true
  become_method: su
  become_user: "{{ wallet_username }}"
  register: wallet_entrys



- name: create wallet entrys if they not exist
  shell: qdbus org.kde.kwalletd5 /modules/kwalletd5 writePassword "$(qdbus org.kde.kwalletd5 /modules/kwalletd5 org.kde.KWallet.open {{ passwd_wallet }} 0 "{{ passwd_folder }}")" "{{ passwd_folder }}" "{{ item.key }}" "{{ item.value }}" "{{ passwd_folder }}"
  become: true
  become_method: su
  become_user: "{{ wallet_username }}"
  when: not wallet_entrys.stdout is search(item.key)
  loop: default_entries









# - name: check if kdewalletfolder exists 2
#   shell: qdbus org.kde.kwalletd5 /modules/kwalletd5 folderList "$(qdbus org.kde.kwalletd5 /modules/kwalletd5 org.kde.KWallet.open {{ passwd_wallet }} 0 "{{ passwd_folder }}")" "{{ passwd_folder }}" 
#   become: true
#   become_method: su
#   become_user: "{{ wallet_username }}"
#   register: walletfolders

# - name: does kdewalletfolder exists 2
#   ansible.builtin.debug:
#     msg: "daag 2"
#   when: walletfolders.stdout is search(passwd_folder)

# - name: does kdewalletfolder not exists 2
#   ansible.builtin.debug:
#     msg: "not daag 2"
#   when: not walletfolders.stdout is search(passwd_folder)