---

- name: Creates ansiblepull directory
  file:
    path: /ansiblepull
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Creates ansiblepull directory
  file:
    path: /ansiblepull/scripts
    state: directory
    owner: root
    group: root
    mode: 0755

- name: copy pull scripts
  copy:
    src: "{{ item }}"
    dest: "/ansiblepull/scripts/{{ item }}"
    owner: "root"
    group: "root"
    mode: '0755'
  loop:
    - ansible_pull_disable.sh
    - ansible_pull_status.sh
    - ansible_pull_disable_status.sh
    - ansible_pull_reenable.sh
    - ansible_pull_reenable_user.sh

- name: install units for ansible-pull
  template:
    dest: /etc/systemd/system
    src: "{{ item }}"
  loop:
    - ansible-pull.service
    - ansible-pull.timer
    - ansible-pull_reenable.service

# - name: enable ansible-pull timer
#   service:
#     name: ansible-pull.timer
#     state: started
#     enabled: yes

- name: enable ansible-pull timer
  ansible.builtin.file:
    src: "/etc/systemd/system/{{ item }}"
    dest: "/etc/systemd/system/multi-user.target.wants/{{ item }}"
    owner: root
    group: root
    state: link
  loop:
    - ansible-pull.timer
    - ansible-pull_reenable.service


