---

- name: Install needed packages
  apt:
    state: latest
    name: "{{ item }}" 
  loop:
    - tilix
    - zsh
    - dbus-x11
    - dconf-service
    - dconf-cli
    - git

- name: remove kde konsole
  apt:
    state: absent
    name: "konsole" 

- name: copy tilix config
  copy:
    src: "{{ role_path }}/files/tilix.dconf"
    dest: "/home/{{ terminal_username }}/tilix.dconf"
    owner: "{{ terminal_username }}"
    group: "{{ terminal_username }}"
    mode: '0644'

- name: load tilix config
  become: true
  become_method: su
  become_user: "{{ terminal_username }}"
  shell: dbus-launch dconf load /com/gexperts/Tilix/ < /home/{{ terminal_username }}/tilix.dconf

- name: remove tilix config
  file:
    path: "/home/{{ terminal_username }}/tilix.dconf"
    state: absent

- name: Install/update Oh My Zsh
  git:
    repo: 'https://github.com/robbyrussell/oh-my-zsh.git'
    dest: ~/.oh-my-zsh
    depth: 1

- name: Install zsh-autosuggestions
  git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions'
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    depth: 1

- name: Install/update Oh My Zsh terminal user
  become: true
  become_method: su
  become_user: "{{ terminal_username }}"
  git:
    repo: 'https://github.com/robbyrussell/oh-my-zsh.git'
    dest: ~/.oh-my-zsh
    depth: 1

- name: Install zsh-autosuggestions terminal user
  become: true
  become_method: su
  become_user: "{{ terminal_username }}"
  git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions'
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    depth: 1
    
  