---

- name: Install needed packages
  apt:
    state: latest
    name: "{{ item }}" 
  loop:
    - tilix
    - zsh

- name: remove kde konsole
  apt:
    state: absent
    name: "konsole" 


- name: load tilix config
  shell: dbus-launch dconf load /com/gexperts/Tilix/ < {{ role_path }}/files/tilix.dconf