---

- name: clone repos
  become: true
  become_method: su
  become_user: "{{ desktop_username }}"
  git:
    repo: "https://github.com/lipido/kargos.git"
    dest: '/home/{{ desktop_username }}/software/kargos'

- name: check if kargos already installed
  become: true
  become_method: su
  become_user: "{{ desktop_username }}"
  stat:
    path: '/home/{{ desktop_username }}/.local/share/plasma/plasmoids/org.kde.kargos'
  register: kargos_installed

- shell: 'cd /home/{{ desktop_username }}/software/kargos && kpackagetool5 -t Plasma/Applet --remove plasmoid'
  args:
    executable: /bin/bash
  become: true
  become_method: su
  become_user: "{{ desktop_username }}"
  when: kargos_installed.stat.exists   

- shell: 'cd /home/{{ desktop_username }}/software/kargos && kpackagetool5 -t Plasma/Applet --install plasmoid'
  args:
    executable: /bin/bash
  become: true
  become_method: su
  become_user: "{{ desktop_username }}"

- name: Configure Plasma shell
  become: true
  become_method: su
  become_user: "{{ desktop_username }}"
  block:
  - tempfile:
      state: file
    register: plasma_js
    changed_when: false
  - copy:
      src: configure_plasma_shell.js
      dest: '{{ plasma_js.path }}'
    changed_when: false
  - shell: 'qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript "$(<{{ plasma_js.path }})"'
    args:
        executable: /bin/bash
    # TODO: any easy way to tell when this changed?
    changed_when: false