---

- name: Install plymouth packages
  apt:
    state: latest
    name: "{{ item }}" 
  loop:
    - plymouth 
    - plymouth-themes
    - plymouth-theme-breeze
    - kde-config-plymouth
    - firmware-linux

- name: Check if splash screen in grub is enabled
  shell: grep GRUB_CMDLINE_LINUX_DEFAULT /etc/default/grub | grep -c "splash"
  register: grub_splash_status
  ignore_errors: true

- name: Enable splash screen in grub
  lineinfile: dest="/etc/default/grub" regexp='GRUB_CMDLINE_LINUX_DEFAULT="(.*)"' line='GRUB_CMDLINE_LINUX_DEFAULT="\1 splash"' backrefs=yes
  when: grub_splash_status.stdout == "0"

- name: update-grub
  shell: update-grub2
  when: grub_splash_status.stdout == "0"


- name: Check if theme exists
  stat:
    path: /usr/share/plymouth/themes/ams
  register: ams_theme_exists

- name: copy plymouth theme
  copy:
    src: "{{ role_path }}/files/ams"
    dest: "/usr/share/plymouth/themes/ams"
    owner: "root"
    group: "root"
  when: not ams_theme_exists.stat.exists
  register: copy_plymouth_theme_status

- name: Enable plymouth daemon config
  lineinfile: dest="/etc/plymouth/plymouthd.conf" regexp='#\[Daemon\]' line='[Daemon]' backrefs=yes
  register: daemon_comment_status


- name:  Enable plymouth theme config
  lineinfile: dest="/etc/plymouth/plymouthd.conf" regexp='#Theme=(.*)' line='Theme=\1' backrefs=yes
  register: theme_comment_status


- name:  Enable plymouth breeze theme 
  lineinfile: dest="/etc/plymouth/plymouthd.conf" regexp='Theme=(.*)' line='Theme=ams' backrefs=yes
  register: theme_status

- name: update initrd
  shell: update-initramfs -u -k all
  when: daemon_comment_status|changed or theme_comment_status|changed or theme_status|changed or copy_plymouth_theme_status|changed