---

- name: Install plymouth packages
  apt:
    state: latest
    name: "{{ item }}" 
  loop:
    - plymouth 
    - plymouth-themes
    - plymouth-theme-breeze
    - kde-config-plymouth
    - firmware-linux

- name: Check if splash screen in grub is enabled
  shell: grep GRUB_CMDLINE_LINUX_DEFAULT /etc/default/grub | grep -c "splash"
  register: grub_splash_status
  ignore_errors: true

- name: Enable splash screen in grub
  lineinfile: dest="/etc/default/grub" regexp='GRUB_CMDLINE_LINUX_DEFAULT="(.*)"' line='GRUB_CMDLINE_LINUX_DEFAULT="\1 splash"' backrefs=yes
  when: grub_splash_status.stdout == "0"

- name: update-grub
  shell: update-grub2
  when: grub_splash_status.stdout == "0"




# - name: Check if plymouth Daemon section is enabled
#   shell: grep '\[Daemon\]' /etc/plymouth/plymouthd.conf | grep -c "#"
#   register: daemon_comment_status
#   ignore_errors: true

- name: Enable plymouth daemon config
  lineinfile: dest="/etc/plymouth/plymouthd.conf" regexp='#\[Daemon\]' line='[Daemon]' backrefs=yes
  # when: daemon_comment_status.stdout == "0"

# - name: Check if plymouth Theme section is enabled
#   shell: grep Theme /etc/plymouth/plymouthd.conf | grep -c "#"
#   register: theme_comment_status
#   ignore_errors: true

- name:  Enable plymouth theme config
  lineinfile: dest="/etc/plymouth/plymouthd.conf" regexp='#Theme=(.*)' line='Theme=\1' backrefs=yes
  # when: daemon_comment_status.stdout == "0"

# - name: Check if plymouth theme is setted
#   shell: grep Theme /etc/plymouth/plymouthd.conf | grep -c "breeze"
#   register: theme_status
#   ignore_errors: true










# - name: update-grub
#   shell: plymouth-set-default-theme -R breeze 


